language: node_js
node_js:
  - "node"
  - "6"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g codecov
script:
  - yarn run ci
after_script:
  - yarn run codecov
  - yarn run deploy
