language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - yarn
  - npm install -g codecov
script:
  - yarn run ci
after_script:
  - yarn run codecov
  - yarn run deploy
