language: node_js
node_js:
  - "6"
# before_install:
  # CI server install taobao npm packages too slow.
  # - rm -rf ./yarn.lock
install:
  - npm install -g codecov
  - npm install
script:
  - npm run ci
  - npm run build # build project for deploy
after_script:
  - npm run codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
